=== hoenir-space/core/res/xsd/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://hoenir.space/resource/schema/data" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="data" type="data:dataType" xmlns:data="https://hoenir.space/resource/schema/data"/>
    <xs:simpleType name="UUIDType">
        <xs:restriction base="xs:string">
            <xs:pattern value="hde:(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="edgeType">
        <xs:simpleContent>
            <xs:extension base="xs:string" xmlns:data="https://hoenir.space/resource/schema/data">
                <xs:attribute type="data:UUIDType" name="type" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
                <xs:attribute type="xs:float" name="weight" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
                <xs:attribute type="data:UUIDType" name="target" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="edgesType">
        <xs:sequence>
            <xs:element type="data:edgeType" name="edge" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="data:UUIDType" xmlns:data="https://hoenir.space/resource/schema/data">
                <xs:attribute type="data:UUIDType" name="type" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="propertiesType">
        <xs:sequence>
            <xs:element type="data:propertyType" name="property" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vertexType">
        <xs:sequence>
            <xs:element type="data:UUIDType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            <xs:element type="data:UUIDType" name="type" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            <xs:element type="data:propertiesType" name="properties" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            <xs:element type="data:edgesType" name="edges" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="graphType">
        <xs:sequence>
            <xs:element type="data:UUIDType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            <xs:element type="data:UUIDType" name="type" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            <xs:element type="data:vertexType" name="vertex" minOccurs="1" maxOccurs="unbounded" xmlns:data="https://hoenir.space/resource/schema/data"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dataType">
            <xs:choice>
                <xs:element type="data:graphType" name="graph" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
                <xs:element type="data:vertexType" name="vertex" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
            </xs:choice>
    </xs:complexType>
</xs:schema>

=== hoenir-space/core/res/xml/data_vertex.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="https://hoenir.space/resource/schema/data"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://hoenir.space/resource/schema/data ../xsd/data.xsd">
    <vertex>
        <id>hde:hoenir.[space|blue|eu|at]:7c4b388b-6360-4678-b709-ff0d6e38c17b</id>
        <type>hde:hoenir.[space|blue|eu|at]:31842730-17d0-4118-a8cd-a9b6993b80e0</type>
        <properties>
            <property type="hde:hoenir.[space|blue|eu|at]:23396456-9f47-4e96-925f-f15bdd238e26">Bla Bla dfgdfg</property>
            <property type="hde:hoenir.[space|blue|eu|at]:5ab7b612-d262-423e-abae-f9593b01a560">Bla Bla</property>
        </properties>
        <edges>
            <edge type="hde:hoenir.[space|blue|eu|at]:70879393-26f6-419a-a8d4-a5bbf57ceccb"
                  weight="1.0"
                  target="hde:hoenir.[space|blue|eu|at]:01603165-6ee5-43d9-98f6-d95e3feda8f4"/>
        </edges>
    </vertex>
</data>
